version: '3.4'

services:
  redis:
    image: redis/redis-stack
    volumes:
      - lv_redis:/data/
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: "--appendonly yes --save 60 1"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s  # Check every 10 seconds
      retries: 3     # Retry 3 times before considering unhealthy

  feedmanager.silo:
    image: csrakowski/feedmanagersilo
    build:
      context: .
      dockerfile: src/FeedManager.Silo/Dockerfile
      no_cache: true
    volumes:
      - lv_silo:/var/log/
    ports:
      - "8443:443"
    environment:
      REDIS_URL: "redis:6379"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost/healthCheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 5s
    depends_on:
      redis:
        condition: service_healthy

  feedmanager.webclient:
    image: csrakowski/feedmanagerwebclient
    build:
      context: .
      dockerfile: src/FeedManager.WebClient/Dockerfile
      no_cache: true
    volumes:
      - lv_webclient:/var/log/
    ports:
      - "5443:443"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost/healthCheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
      start_interval: 5s
    depends_on:
      feedmanager.silo:
        condition: service_healthy

  krakend:
    image: devopsfaith/krakend
    volumes:
      - lv_krakend:/etc/krakend/
    ports:
      - "8080:8080"
      - "8090:8090"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost:8080/__health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
      start_interval: 5s
    depends_on:
      feedmanager.silo:
        condition: service_healthy


volumes:
  lv_redis: {}
  lv_silo: {}
  lv_webclient: {}
  lv_krakend: {}
