version: '3.4'

services:
  feedmanager.silo:
    image: ${DOCKER_REGISTRY-}feedmanagersilo
    build:
      context: .
      dockerfile: src/FeedManager.Silo/Dockerfile
    volumes:
      - lv_silo:/log/
    ports:
      - "8443:443"
    # healthcheck:
    #   test: curl -f https://localhost/healthCheck || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    #   start_interval: 5s

  feedmanager.webclient:
    image: ${DOCKER_REGISTRY-}feedmanagerwebclient
    build:
      context: .
      dockerfile: src/FeedManager.WebClient/Dockerfile
    volumes:
      - lv_webclient:/log/
    ports:
      - "5443:443"
    # healthcheck:
    #   test: curl -f https://localhost/healthCheck || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    #   start_interval: 5s
    depends_on:
      feedmanager.silo:
        condition: service_started

volumes:
  lv_silo: {}
  lv_webclient: {}
