name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages.
    # Once published, the packages are scoped to the account defined here.
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image for FeedManager.Silo
      run: docker build --no-cache . --file src/FeedManager.Silo/Dockerfile --tag ${{ env.REGISTRY }}/csrakowski/feedmanagersilo:$(date +%s) --tag ${{ env.REGISTRY }}/csrakowski/feedmanagersilo:latest --push

    - name: Build the Docker image for FeedManager.WebClient
      run: docker build --no-cache . --file src/FeedManager.WebClient/Dockerfile --tag ${{ env.REGISTRY }}/csrakowski/feedmanagerweb:$(date +%s) --tag ${{ env.REGISTRY }}/csrakowski/feedmanagerweb:latest --push
