name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for FeedManager.Silo
      run: docker build --no-cache . --file src/FeedManager.Silo/Dockerfile --tag csrakowski/feedmanagersilo:$(date +%s)
    - name: Build the Docker image for FeedManager.WebClient
      run: docker build --no-cache . --file src/FeedManager.WebClient/Dockerfile --tag csrakowski/feedmanagerweb:$(date +%s)
